name: web_links
version: 0.0.2
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: Polymer application with web links.
homepage: http://ondart.me/
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
